name = "novaboard-refreshed"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]

main = "./.cloudflare/worker.js"

[build]
command = "npm run build"
cwd = "."
dist = ".cloudflare/static"

[site]
bucket = ".cloudflare/static" 